version: "3.8"

volumes:
    static_volume:
    postgres_data:

services:

    nginx:
        build: ./nginx
        container_name: notino-nginx
        ports:
            - "8000:80"
        volumes:
            - static_volume:/notino_watcher/staticfiles
        depends_on:
            - app

    redis:
        image: "redis:alpine"
        container_name: notino-redis
        ports:
            - "6379:6379"

    app:
        build: ./src
        container_name: notino-app
        command: gunicorn notino_watcher.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
            - static_volume:/notino_watcher/staticfiles
        expose:
            - 8000
        environment:
            - DEBUG=0
            - ALLOWED_HOSTS=localhost,127.0.0.1,*
            - CELERY_BROKER=redis://redis:6379/0
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - ADDRESSEE=your_email
        depends_on:
            - redis
            - db

    celery-worker:
        build: ./src
        container_name: notino-celery-worker
        command: celery -A notino_watcher worker -l INFO
        volumes:
            - .:/usr/src/app
            - static_volume:/notino_watcher/staticfiles
        environment:
            - DEBUG=0
            - ALLOWED_HOSTS=localhost,127.0.0.1,*
            - CELERY_BROKER=redis://redis:6379/0
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        depends_on:
            - app
            - redis
            - db

    celery-beat:
        build: ./src
        container_name: notino-celery-beat
        command: celery -A notino_watcher worker -l INFO
        volumes:
            - .:/usr/src/app
            - static_volume:/notino_watcher/staticfiles
        environment:
            - DEBUG=0
            - ALLOWED_HOSTS=localhost,127.0.0.1,*
            - CELERY_BROKER=redis://redis:6379/0
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        depends_on:
            - app
            - redis
            - db

    db:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        container_name: notino-db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/notino/
        volumes:
            - postgres_data:/var/lib/postgresql/data