FROM python:3.7
ENV PYTHONUNBUFFERED=1
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /notino_watcher/src
WORKDIR /notino_watcher/src
COPY ./ /notino_watcher/src/

RUN apt-get update
RUN apt-get install --yes --no-install-recommends apt-utils
RUN pip install --upgrade pip
RUN apt-get -q update && apt-get -qy install netcat
RUN apt-get install dos2unix
RUN pip install -r requirements.txt

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
# https://github.com/ufoscout/docker-compose-wait/blob/master/LICENSE
RUN chmod +x /wait
RUN chmod +x /notino_watcher/src/entrypoint.sh
RUN dos2unix /notino_watcher/src/entrypoint.sh

ENTRYPOINT ["/notino_watcher/src/entrypoint.sh"]